### ISSUE TITLE
How to build 'wlan.ko' file.

### ISSUE THREAD

**Issue by nuribom1** [b1ad3runn3r/drag-kernel-t975#3]
I want to build the SM-T970 kernel source to the Qualcomm Wi-Fi driver 'wlan.ko' file.
Even if I run the 'build_kernel.sh' file, the 'wlan.ko' file is not generated.
Is there a way to create the 'wlan.ko' file?
Thanks.

**Comment by b1ad3runn3r** [comment]
Hi, I am not sure whether this kernel is applicable for your situation because it is supposed to be for SM-T975 only

**Comment by nuribom1** [comment]
Yes. I am using SM-T975, not SM-T970.
I am applying another vendor's wifi driver, and I am referencing it because it is similar to the qualcomm wifi driver. 
However, when building the qualcomm wifi driver (./driver/net/wireless/qualcomm/) , a module file called 'wlan.ko' is created, but when I build with this git's 'build_kernel.sh' file, the 'wlan.ko' module file is not created in the out folder. No other ko files are created either. 
I would like to ask if I have set it up wrong.
Is the 'wlan.ko' file related to the wifi driver created?

Thanks
